//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace Optimization.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        internal static Settings DefaultInstance { get => DefaultInstance1; set => DefaultInstance1 = value; }
        internal static Settings DefaultInstance1 { get => defaultInstance; set => defaultInstance = value; }
        
        [UserScopedSetting()]
        [DefaultSettingValue("0,0")]
        public string CustomLocation
        {
            get => (string)this["CustomLocation"];
            set => this["CustomLocation"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("935,600")]
        public string CustomSize
        {
            get => (string)this["CustomSize"];
            set => this["CustomSize"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        public bool IsMaximized
        {
            get => (bool)this["IsMaximized"];
            set => this["IsMaximized"] = value;
        }
    }
}
